#!/usr/bin/env bash
# Regenerates Tests/SloopAppTests/KeyFixtures.swift.
#
# The fixtures are throwaway keys made by ssh-keygen. They authorize nothing.
# They exist so KeyValidator is measured against real OpenSSH output — both the
# private key formats it must parse and the .pub lines it must reproduce —
# rather than against our own idea of those formats, which is exactly the kind
# of self-agreement that let a backend ship unable to read Ed25519 keys.
#
# Run from the repository root. Rerunning produces different keys; that is
# fine, nothing pins their contents.
set -euo pipefail

out="Tests/SloopAppTests/KeyFixtures.swift"
[ -d "$(dirname "$out")" ] || { echo "run me from the repository root" >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

ssh-keygen -q -t ed25519 -N ""        -C fixture-ed25519    -f "$tmp/k_ed"
ssh-keygen -q -t ed25519 -N "hunter2" -C fixture-ed25519-pw -f "$tmp/k_ed_pw"
ssh-keygen -q -t ecdsa   -N ""        -C fixture-ecdsa      -f "$tmp/k_ec"
ssh-keygen -q -t rsa -b 2048 -N ""    -C fixture-rsa        -f "$tmp/k_rsa"

# The encrypted fixtures above are OpenSSH containers, which libssh2 decrypts
# itself. `-m PEM` produces the legacy `Proc-Type: 4,ENCRYPTED` envelope, which
# it hands to OpenSSL instead — and OpenSSL calls the passphrase callback for
# it whether or not one was supplied. Validating this key with no passphrase
# used to segfault the app; only a fixture in this format can catch that.
ssh-keygen -q -t rsa -b 2048 -m PEM -N "hunter2" -C fixture-rsa-legacy-pw -f "$tmp/k_rsa_legacy_pw"

emit() { printf '    static let %s = """\n%s\n"""\n\n' "$1" "$(cat "$2")"; }

{
  echo "// Sloop — Copyright (C) 2026 Matthew Szatmary"
  echo "// GPL-3.0 with additional terms under §7 — see LICENSE and THIRD-PARTY-NOTICES.md"
  echo ""
  echo "// Throwaway keys generated by ssh-keygen solely as test fixtures. They"
  echo "// authorize nothing and exist so KeyValidator is measured against real"
  echo "// OpenSSH output rather than against our own idea of the format."
  echo "//"
  echo "// Regenerate with Scripts/generate-key-fixtures.sh."
  echo ""
  echo "enum KeyFixtures {"
  emit ed25519PEM                  "$tmp/k_ed"
  emit ed25519PublicLine           "$tmp/k_ed.pub"
  emit ed25519PassphrasePEM        "$tmp/k_ed_pw"
  emit ed25519PassphrasePublicLine "$tmp/k_ed_pw.pub"
  emit ecdsaPEM                    "$tmp/k_ec"
  emit ecdsaPublicLine             "$tmp/k_ec.pub"
  emit rsaPEM                      "$tmp/k_rsa"
  emit rsaPublicLine               "$tmp/k_rsa.pub"
  emit rsaLegacyEncryptedPEM       "$tmp/k_rsa_legacy_pw"
  emit rsaLegacyEncryptedPublicLine "$tmp/k_rsa_legacy_pw.pub"
  echo '    static let passphrase = "hunter2"'
  echo "}"
} > "$out"

echo "wrote $out"
